<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Products</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cb59dd42-ff63-4bed-b36e-0ffd6918577c</testSuiteGuid>
   <testCaseLink>
      <guid>3ac048c6-b157-4623-97a2-480f68d53abc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product/TC Add Review invalid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18530567-81a1-4bb0-acaf-a74c3dbd349e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea07e6fb-f159-48f2-a531-246662173d43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product/TC Add review valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80c5330d-119d-49ee-969e-87fa5aa80362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44e1ae21-bdb7-433e-be13-0c905446dfcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db460169-6611-40b8-ac65-45fd88716461</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c8b08a8-c664-4081-adac-a6f4a22fdccb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product/TC Update Cart with Crazy Amount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77b4b72b-247e-4c9c-ba15-a098e0434643</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bfa5be5-92d1-4572-8863-a396cbdf3244</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product/TC Update Cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb2ecf90-741b-4c31-bff9-cb1fa25245ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92b212a6-9396-4a6e-82d7-0ae35c6c0ba5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product/WP-10 Gibran - TC Add to Cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
