<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_user_password-297</name>
   <tag></tag>
   <elementGuidId>a2176999-23dc-476c-968b-ba3fe3fab66c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_password-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user_password-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e92f8d4b-c78c-4069-a79e-0e4906f70b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid</value>
      <webElementGuid>856a0c75-ff30-422b-b46e-78b59e64f999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7750e5fa-7182-4063-af87-c18ee9eed488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_password-297</value>
      <webElementGuid>98b1707a-00b5-41a5-a5e3-b6d3602d1159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_password-297</value>
      <webElementGuid>6eca2079-95a7-46d2-acd9-cd5d08ee61b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>user_password</value>
      <webElementGuid>5acc03e3-c740-427a-a7da-78632a6fdf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password-297&quot;)</value>
      <webElementGuid>5cf2b2ad-11a5-4ed9-82d2-669b22fc4171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_password-297']</value>
      <webElementGuid>ca4d0c49-7d40-48b8-8210-f11569ca9588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_user_password']/div[2]/input</value>
      <webElementGuid>2065f928-77ed-4352-b0e5-3410ee946e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>53897866-921a-4448-b1ba-4ecde5736e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'user_password-297' and @id = 'user_password-297']</value>
      <webElementGuid>7cf8497d-4826-40d4-b792-561d69974345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
