<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_Relative_adress-297</name>
   <tag></tag>
   <elementGuidId>d16048c1-df26-42eb-a2cd-5a5a4009eecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Relative_adress-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Relative_adress-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>227cc89a-57c8-4dfb-8fca-0369be2c3897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>94d8d3f7-5c51-422e-bba1-006af8a9f613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field valid </value>
      <webElementGuid>5bd09e0a-9d9a-4433-bcee-58d2e8d4d0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0f27fb3-c638-41a2-bdb1-edfa7a94446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>f6347788-092e-45b7-98e5-3abbed053b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>70781116-cfa3-4cd0-97d5-b74ef8e6540b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>Relative_adress</value>
      <webElementGuid>0481bb41-61d2-42a8-b014-399c5b66732d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Relative_adress-297&quot;)</value>
      <webElementGuid>f61a08de-ca94-46d3-8794-de887f344c29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Relative_adress-297']</value>
      <webElementGuid>2c0b3088-6ae7-4ea0-a687-1f8a5471d5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_Relative_adress']/div[2]/input</value>
      <webElementGuid>cb6e5feb-6d87-4bfd-acfe-a97f78f8a5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>211922b5-0cd4-4502-8528-128c24f52c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Relative_adress-297' and @id = 'Relative_adress-297']</value>
      <webElementGuid>22f85548-1e3e-410a-86cd-2b9fb11be402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
