<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ada</name>
   <tag></tag>
   <elementGuidId>a6d3aaf9-f3d2-4862-8300-fd286eb7a31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comment-19']/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.description > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>21a21526-8bb0-4898-8b16-d3ac30ee5164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ada</value>
      <webElementGuid>9fb16cc6-16bf-4549-86ac-dc0c594ad6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment-19&quot;)/div[@class=&quot;comment-text&quot;]/div[@class=&quot;description&quot;]/p[1]</value>
      <webElementGuid>df6304df-536c-40ec-a055-c70ce47df010</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comment-19']/div/div[2]/p</value>
      <webElementGuid>c4b7bf31-5b48-4cd3-a4cc-cf5ea4f34e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your review is awaiting approval'])[1]/following::p[1]</value>
      <webElementGuid>116f2198-01bf-49b1-9047-b75811bd69a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel reply'])[1]/preceding::p[1]</value>
      <webElementGuid>db26204e-0a52-4830-85b4-2c9dabed4f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ada']/parent::*</value>
      <webElementGuid>7000aa84-2bb2-4aab-babf-571f5b7d73ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>c91eaaa0-d346-4dd5-8dfc-294f842ad7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ada' or . = 'ada')]</value>
      <webElementGuid>943b709c-5c85-47e3-acc6-2d35fa59e9ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
