<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Error Please fill the required fields</name>
   <tag></tag>
   <elementGuidId>f530a5a4-7f07-4441-8dbc-bf858a6d5d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='error-page']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>560caa6e-c666-4eb9-806e-049800a983af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error: Please fill the required fields.</value>
      <webElementGuid>6861ddef-16fb-4e5a-b4d5-9d2ed92d7d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-page&quot;)/div[@class=&quot;wp-die-message&quot;]/p[1]</value>
      <webElementGuid>3a8b2a46-b024-4cf9-891b-18940194ee6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='error-page']/div/p</value>
      <webElementGuid>11423e68-5520-4964-87f7-95e2ef108bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='« Back'])[1]/preceding::p[1]</value>
      <webElementGuid>359ed115-d10d-4d30-9f87-d92b14b5e064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)=': Please fill the required fields.']/parent::*</value>
      <webElementGuid>51773c76-5000-4565-b684-c68641c22535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ba700d4c-43e8-416f-83b7-0af4368bae10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Error: Please fill the required fields.' or . = 'Error: Please fill the required fields.')]</value>
      <webElementGuid>ee845064-d607-485f-a67d-1738a34aa838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
