<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_View cart Beanie has been added to your cart</name>
   <tag></tag>
   <elementGuidId>0f04dc39-bbcd-4fb8-b647-7f8d02eaa49d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.with-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0b8fa640-5ed8-4ac2-9a79-62f9d760134b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>with-button</value>
      <webElementGuid>367da7a2-df33-4079-b10d-f5038be672e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View cart “Beanie” has been added to your cart.</value>
      <webElementGuid>b187fd82-6a81-47e2-a753-241ee2122d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;woocommerce-notices-wrapper&quot;]/div[@class=&quot;woocommerce-message&quot;]/p[@class=&quot;with-button&quot;]</value>
      <webElementGuid>d02766a2-7094-44cc-a68a-7f640ba93af7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/p</value>
      <webElementGuid>b687eea6-67d4-45a7-8499-0cd3616dd8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::p[1]</value>
      <webElementGuid>a3c832e8-38d8-4ecb-8426-8407f4fd885d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for:'])[1]/following::p[1]</value>
      <webElementGuid>8fc07155-eadd-487d-b12b-385686458d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale!'])[1]/preceding::p[1]</value>
      <webElementGuid>610c5e87-b044-4b82-9bc3-7570a85e10f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='“Beanie” has been added to your cart.']/parent::*</value>
      <webElementGuid>0c878097-ae8b-4a33-bb8d-443f9a49f19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/p</value>
      <webElementGuid>f24b55b8-40e5-4d2b-a87f-0a38f276bd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'View cart “Beanie” has been added to your cart.' or . = 'View cart “Beanie” has been added to your cart.')]</value>
      <webElementGuid>fcf30c00-0c92-46ac-b76a-10f5a94d02c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
