<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Beanie quantity_cartac1dd209cbcc5e5d1c6e28598e8cbbe8qty</name>
   <tag></tag>
   <elementGuidId>864a2c45-9d61-4d08-a40c-cd338f4364dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity_62c913df6c8ee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_62c913df6c8ee']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @id = 'quantity_62c913df6c8ee' and @name = 'cart[ac1dd209cbcc5e5d1c6e28598e8cbbe8][qty]' and @value = '1' and @title = 'Qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79b73489-caa5-4f95-af5b-c8ff8e156046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6eeb2f99-a88a-4042-a21d-1f473722c059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_62c913df6c8ee</value>
      <webElementGuid>36de64df-e0ff-4ca4-b582-c98c4ef17249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>92503966-8792-4bbb-95b1-8234034487ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e0aad820-029f-4abe-9b7f-7561397a48ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff778cb2-3808-43ce-b08f-c358f0f3eba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[ac1dd209cbcc5e5d1c6e28598e8cbbe8][qty]</value>
      <webElementGuid>f5e23fcd-917b-40ba-a376-9c5cbeb87f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9b00c3cc-894f-4db9-9d05-13226e85a0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>0343ba90-31a1-4d38-b9b4-a954b6d27903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>602a0b1a-3a83-4045-9d57-cf39c0367130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a1d15743-61bf-45b0-8e73-9267e718d743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c89213ab-16a0-456e-b3e0-21985b85578a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_62c913df6c8ee&quot;)</value>
      <webElementGuid>c92799e0-71a7-4871-bced-541f0b4569a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_62c913df6c8ee']</value>
      <webElementGuid>d5a500c7-be72-4271-b9f1-5946c44e0aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-53']/div/div/form/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>b3c0418c-7999-47fa-bcfd-a1c0ae95927c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/input</value>
      <webElementGuid>a0e31a16-36f4-4b6f-8520-d71084864bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'string' and @id = 'quantity_62c913df6c8ee' and @name = 'cart[ac1dd209cbcc5e5d1c6e28598e8cbbe8][qty]' and @title = 'Qty']</value>
      <webElementGuid>f807b96f-8535-42a0-9681-8ea3faa48d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
